-- Requêtes jours d'ouverture
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Lundi', '10h-18h');
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Mardi', '10h-18h');
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Mercredi', '10h-18h');
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Jeudi', '10h-18h');
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Vendredi', '10h-18h');
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Samedi', '10h-19h');
INSERT INTO `HORAIRES` (`ID`, `JOUR`, `HEURE`) VALUES (NULL, 'Dimanche', '10h-19h');

-- Requêtes animaux marais 
INSERT INTO "animaux"('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, 'Flanders', '2017-08-25', '500g de poissons', 'Très bon', 'marais', 'Lutra sumatrana', "La loutre de Sumatra est une espèce en danger selon l\’IUCN (Union Internationale pour la Conservation de la Nature) et est inscrite au programme européen pour les espèces menacées (EEP).","La loutre de Sumatra est l'une des loutres les plus rares et les moins étudiées, vivant principalement dans les rivières et marécages d'Asie du Sud-Est. Contrairement à d'autres loutres, elle a une tache blanche distincte sur son menton et sa gorge. Elle est également remarquable pour ses griffes rétractiles, une caractéristique rare parmi les loutres, qui lui permet une meilleure manipulation des proies.","","2024-05-10");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, 'Sobek', '1995-11-10', "5kg de viande crue et 1kg d’os", 'Très bon', 'marais', 'Crocodylus niloticus', "Le crocodile du Nil est une espèce faisant l\’objet d\’une préoccupation mineure selon l’IUCN (Union Internationale pour la Conservation de la Nature).", "Le crocodile du Nil, est un prédateur redoutable capable de rester submergé pendant de longues périodes, attendant patiemment sa proie. Leurs mâchoires puissantes exercent une pression écrasante, mais étrangement, leurs muscles pour ouvrir la gueule sont assez faibles. Malgré leur apparence préhistorique, les crocodiles du Nil sont des parents attentionnés, protégeant leurs œufs et leurs jeunes avec dévouement.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Evangéline", "1992-10-15", "5kg de viande crue toutes les 2 semaines", "Très bon", "marais", "Alligator mississippiensis", "L\’alligator est une espèce faisant l’objet d’une préoccupation mineure selon l’IUCN (Union Internationale pour la Conservation de la Nature).", "L'alligator est un maître du camouflage, utilisant sa couleur pour se fondre dans son environnement aquatique. Contrairement aux idées reçues, ils peuvent également réguler leur flottabilité en avalant de l'air, leur permettant de rester partiellement immergés sans bouger. Ils ont une dentition impressionnante, mais leurs muscles pour ouvrir la gueule sont faibles et il est possible de les maintenir fermées avec quelques bandes élastiques.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Mara", "2012-05-12", "700g de poissons et 400g de viande crue", "marais", "Paleosuchus trigonatus", "Le caïman à museau large est une espèce faisant l\’objet d\’une préoccupation mineure selon l\’IUCN (Union Internationale pour la Conservation de la Nature).", "Le caïman à museau large est le plus petit des caïmans, atteignant généralement 1,5 à 2 mètres de long. Ce reptile discret possède une carapace osseuse sur le dos et la queue, offrant une protection supplémentaire contre les prédateurs. Il est également connu pour son comportement nocturne et sa capacité à se cacher efficacement dans les eaux sombres des forêts tropicales.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Hector", "2016-08-25", "600g de poissons et crustacés", "Très bon", "marais", "Phoenicopterus roseus", "Le flamant rose est une espèce faisant l’objet d’une préoccupation mineure selon l’IUCN (Union Internationale pour la Conservation de la Nature).", "Le flamant rose doit sa couleur éclatante à son alimentation riche en caroténoïdes, présents dans les algues et les crustacés qu'il consomme. Ces oiseaux filtrent leur nourriture grâce à un mécanisme unique dans leur bec, qui fonctionne comme une passoire. De plus, ils dorment souvent debout sur une seule patte, ce qui aide à conserver leur chaleur corporelle.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Stevy", "2019-08-25", "300g de légumes et plantes et 200g de poissons", "Très bon", "marais", "Myocastor coypus", "Le ragondin est une espèce faisant l’objet d’une préoccupation mineure selon l’IUCN (Union Internationale pour la Conservation de la Nature).", "Le ragondin, est un rongeur semi-aquatique originaire d'Amérique du Sud, facilement reconnaissable à ses grandes incisives orange. Ils possèdent une membrane entre les doigts, ce qui en fait d'excellents nageurs. En raison de leur reproduction rapide, ils peuvent devenir envahissants dans les régions où ils sont introduits.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Sola", "2018-10-16", "60kg d'herbe et feuille et 35kg de fruits et légumes", "Très bon", "marais", "Hippopotamus amphibius", "L’hippopotame est une espèce vulnérable selon l’IUCN (Union Internationale pour la Conservation de la Nature) et est inscrit au programme européen pour les espèces menacées (EEP).", "L’hippopotame commun, peut rester immergé sous l'eau jusqu'à cinq minutes pour se protéger du soleil et des prédateurs. Malgré leur apparence lourde et maladroite, ils peuvent courir à des vitesses surprenantes de 30 km/h sur terre. Leurs puissantes mâchoires peuvent s'ouvrir à près de 150 degrés, exerçant une force de morsure redoutable.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Guetta", "2016-09-09", "200g de végétaux", "Très bon", "marais", "Iguana iguana", "L’iguane est une espèce faisant l’objet d’une préoccupation mineure selon l’IUCN (Union Internationale pour la Conservation de la Nature).", "L'iguane vert, peut détacher sa queue pour échapper aux prédateurs, qui repoussera ensuite avec le temps. Ils ont une excellente vision, capable de détecter les formes et les mouvements à de grandes distances. De plus, ces reptiles sont principalement herbivores, se nourrissant de feuilles, de fleurs et de fruits dans les forêts tropicales.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES (NULL, "Kiang", "1999-01-16", "300g de végétaux", "Très bon", "marais", "Chelonoidis chathamensis", "La tortue est une espèce en danger selon l’IUCN (Union Internationale pour la Conservation de la Nature) et est inscrite au programme européen pour les espèces menacées (EEP).", "La tortue géante de San Cristóbal, est l'une des tortues géantes des Galápagos, connue pour son long cou qui lui permet de brouter des plantes plus hautes. Elles peuvent vivre plus de 100 ans et peuvent survivre sans nourriture ni eau pendant plusieurs mois grâce à leurs réserves internes. Ces tortues jouent un rôle crucial dans leur écosystème en dispersant les graines des plantes qu'elles consomment.", "", "");

INSERT INTO 'animaux' ('id', 'nom', 'naissance', 'alimentation', 'sante', 'habitat', 'nomScientifique', 'descriptionScientifique', 'leSaviezVous', 'image', 'dateVerif') VALUES(NULL, "Dappy", "2021-01-11", "Une quarantaine d'insectes", "Très bon", "marais", "Hyla arborea", "La rainette verte est une espèce faisant l’objet d’une préoccupation mineure selon l’IUCN (Union Internationale pour la Conservation de la Nature).", "La rainette verte est un petit amphibien capable de changer de couleur pour se camoufler, passant du vert au brun selon son environnement. Ces grenouilles possèdent des ventouses au bout de leurs doigts, leur permettant de grimper facilement sur les plantes et les surfaces lisses. Elles sont également connues pour leurs chants puissants, souvent entendus lors des nuits chaudes de printemps et d'été.", "", "");

